/** Single locale bundle for the SPA (split later if i18n is needed). */
export const labels = {
  appTitle: "ARM",
  appSubtitle: "Automatic Ripping Machine",
  appVersion: "v2.23.2",
  comingSoon: "Coming soon",
  nav: {
    home: "Home",
    login: "Login",
    logout: "Logout",
    darkMode: "Dark mode",
    history: "History",
    logs: "Logs",
    settings: "Settings",
    notifications: "Notifications",
  },
  refresh: {
    label: "Refresh",
    ariaLabel: "Refresh system information",
  },
  home: {
    welcome: "Welcome to your Automatic Ripping Machine",
    activeRips: "Active Rips",
    activeRipsEmpty: "No active jobs",
    systemInformation: "System Information",
    loginToViewSystem: "Log in to load system information.",
    loadError: "Could not load system data.",
  },
  jobs: {
    started: "Started",
    stage: "Stage",
    eta: "ETA",
    progressUnknown: "Working, waiting for progress…",
    unnamedJob: "Untitled job",
    loadError: "Could not load active jobs.",
  },
  drives: {
    title: "Drives",
    discLoaded: "Disc loaded",
    empty: "Empty",
    typeUnknown: "Unknown type",
    unnamedDrive: "Drive",
    loadError: "Could not load drives.",
    ripping: "Ripping",
    idle: "Idle",
    stale: "Stale",
  },
  jobDetail: {
    title: "Job Details",
    notFound: "Job not found",
    backToHistory: "Back to history",
    loginToView: "Log in to view job details.",
    loadError: "Could not load job details.",
    retry: "Retry",
    status: "Status",
    disctype: "Disc type",
    year: "Year",
    drive: "Drive",
    started: "Started",
    finished: "Finished",
    duration: "Duration",
    stage: "Stage",
    eta: "ETA",
    progressSection: "Progress",
    progressUnknown: "Working, waiting for progress…",
    tracksSection: "Tracks",
    colTrack: "Track",
    colLength: "Length",
    colAspectRatio: "Aspect ratio",
    colFps: "FPS",
    colMainFeature: "Main feature",
    colStatus: "Status",
    colFilesize: "Size",
    editMetadata: "Edit metadata",
    abandon: "Abandon job",
    delete: "Delete job",
    logSection: "Log",
    viewLog: "View log",
    hideLog: "Hide log",
    logRefresh: "Refresh log",
    logAutoScroll: "Auto-scroll",
    logEmpty: "Log file is empty.",
    logMissing: "Log file not found.",
    logLoadError: "Could not load log file.",
    metadataTitle: "Edit metadata",
    fieldTitle: "Title",
    fieldYear: "Year",
    fieldVideoType: "Video type",
    fieldImdbId: "IMDB ID",
    fieldPosterUrl: "Poster URL",
    fieldYearInvalid: "Year must be 1-4 digits.",
    save: "Save",
    cancel: "Cancel",
    metadataSaveError: "Could not save metadata.",
    metadataSaved: "Metadata updated.",
    metadataError: "Could not update metadata.",
    abandonTitle: "Abandon this job?",
    abandonMessage: "The job will be marked as failed. This cannot be undone.",
    abandonSuccess: "Job abandoned.",
    abandonError: "Could not abandon the job.",
    deleteTitle: "Delete this job?",
    deleteMessage: "The job record will be permanently deleted. This cannot be undone.",
    deleteSuccess: "Job deleted.",
    deleteError: "Could not delete the job.",
    confirm: "Confirm",
  },
  history: {
    title: "History",
    search: "Search titles",
    status: "Status",
    statusAll: "All",
    statusSuccess: "Success",
    statusFail: "Fail",
    statusActive: "Active",
    perPage: "Per page",
    colTitle: "Title",
    colStatus: "Status",
    colDisctype: "Disc type",
    colDrive: "Drive",
    colStarted: "Started",
    colCompleted: "Completed",
    colDuration: "Duration",
    empty: "No jobs found.",
    loadError: "Could not load job history.",
    retry: "Retry",
    total: "Total jobs",
    statusUnknown: "Unknown",
    loginToView: "Log in to view job history.",
  },
  logs: {
    title: "Logs",
    loginToView: "Log in to view logs.",
    loadError: "Could not load log files.",
    retry: "Retry",
    empty: "No log files found.",
    colName: "Name",
    colSize: "Size",
    colModified: "Modified",
    viewerTitle: "Log viewer",
    selectPrompt: "Select a log file to view its contents.",
    modeLabel: "Log mode",
    modeArmcat: "ARM lines",
    modeFull: "Full",
    linesLabel: "Lines",
    linesAll: "All",
    refresh: "Refresh",
    autoRefresh: "Auto-refresh",
    download: "Download",
    downloadError: "Could not download log file.",
    autoScroll: "Auto-scroll",
    contentEmpty: "Log file is empty.",
    contentMissing: "Log file not found.",
    contentLoadError: "Could not load log file.",
  },
  logViewer: {
    filterLabel: "Filter by tool",
    allTools: "All",
    toolNames: {
      ARM: "ARM",
      MKV: "MakeMKV",
      HB: "HandBrake",
      FFMPEG: "FFmpeg",
      ABCDE: "abcde",
    } as Record<string, string>,
    autoScroll: "Auto-scroll",
    refresh: "Refresh",
    loading: "Loading log…",
    empty: "No matching log lines.",
    jsonExpanded: "JSON block (expanded)",
    linesSuffix: "lines",
  },
  notifications: {
    title: "Notifications",
    filter: "Filter",
    filterAll: "All",
    filterUnread: "Unread",
    perPage: "Per page",
    colMessage: "Message",
    colReceived: "Received",
    colStatus: "Status",
    colActions: "Actions",
    statusUnread: "Unread",
    statusRead: "Read",
    statusCleared: "Cleared",
    markRead: "Mark read",
    markReadError: "Could not mark notification as read.",
    clearAll: "Clear all",
    clearAllTitle: "Clear all notifications?",
    clearAllMessage: "All notifications will be cleared from the list. This cannot be undone.",
    clearAllConfirm: "Clear all",
    clearNothing: "No notifications to clear.",
    clearError: "Could not clear notifications.",
    cleared: "Notifications cleared.",
    cancel: "Cancel",
    empty: "No notifications found.",
    emptyUnread: "No unread notifications.",
    loadError: "Could not load notifications.",
    retry: "Retry",
    total: "Total notifications",
    loginToView: "Log in to view notifications.",
  },
  toast: {
    dismiss: "Dismiss",
    pollError: "Could not fetch notifications.",
  },
  settings: {
    title: "Settings",
    loginToView: "Log in to view settings.",
    loadError: "Could not load settings.",
    retry: "Retry",
    readOnly: "The configuration file is read-only. Saving is disabled.",
    tabRipper: "Ripper",
    tabUi: "UI",
    tabAbcde: "abcde",
    tabApprise: "Apprise",
    tabDrives: "Drives",
    tabSecurity: "Security",
    unsavedChanges: "unsaved changes",
    allSaved: "All changes are saved.",
    save: "Save",
    reset: "Reset",
    saved: "Settings saved.",
    saveError: "Could not save settings.",
    invalidInteger: "Enter a valid integer.",
    uiIndexRefresh: "Index refresh (seconds)",
    uiUseIcons: "Use icons",
    uiSaveRemoteImages: "Save remote images",
    uiBootstrapSkin: "Bootstrap skin",
    uiLanguage: "Language",
    uiDatabaseLimit: "Database limit",
    uiNotifyRefresh: "Notify refresh (seconds)",
    abcdeFile: "abcde.conf",
    appriseFile: "apprise.yaml",
    fileSaved: "File saved.",
    fileSaveError: "Could not save file.",
    testNotification: "Send test notification",
    testSent: "Test notification sent.",
    testError: "Could not send test notification.",
    drives: {
      rescan: "Rescan drives",
      scanFound: "Found {count} new drive(s).",
      scanNone: "No new drives found.",
      scanError: "Could not scan for drives.",
      loadError: "Could not load drives.",
      empty: "No drives found.",
      colName: "Name",
      colDescription: "Description",
      colMount: "Mount point",
      colMode: "Mode",
      colJob: "Current job",
      colActions: "Actions",
      modeAuto: "Auto",
      modeManual: "Manual",
      jobById: "Job #{id}",
      eject: "Eject",
      ejected: "Drive ejected.",
      ejectError: "Could not eject drive.",
      edit: "Edit",
      editTitle: "Edit drive",
      fieldName: "Name",
      fieldDescription: "Description",
      fieldMode: "Drive mode",
      cancel: "Cancel",
      save: "Save",
      saved: "Drive updated.",
      saveError: "Could not update drive.",
      manualStart: "Manual start",
      manualStartTitle: "Start a job on this drive?",
      manualStartMessage:
        "ARM will try to start a rip job on this drive. Continue?",
      confirmStart: "Start job",
      manualStarted: "Job start requested.",
      manualStartError: "Could not start job.",
      remove: "Remove",
      removeTitle: "Remove this drive?",
      removeMessage:
        "The drive will disappear from ARM until a new drive scan detects it again. Continue?",
      confirmRemove: "Remove",
      removed: "Drive removed.",
      removeError: "Could not remove drive.",
    },
    security: {
      title: "Change password",
      hint: "Changing your password revokes all API tokens and signs you out everywhere.",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      submit: "Update password",
      required: "Fill in all password fields.",
      tooShort: "New password must be at least 6 characters.",
      mismatch: "New passwords do not match.",
      changed: "Password updated. You have been signed out.",
      error: "Could not change password.",
    },
    sections: {
      general: "General",
      directories: "Directories",
      webServer: "Web server",
      permissions: "File permissions",
      makemkv: "MakeMKV",
      handbrake: "HandBrake",
      ffmpeg: "FFmpeg",
      transcoding: "Transcoding",
      metadata: "Metadata providers",
      emby: "Emby",
      notifications: "Notifications",
      manual: "Manual control",
      misc: "Miscellaneous",
    },
  },
  login: {
    title: "Sign in",
    username: "Username",
    password: "Password",
    submit: "Sign in",
    error: "Sign-in failed. Check your username and password.",
  },
  system: {
    cardTitle: "System",
    memoryTitle: "System Memory",
    storageTitle: "Storage",
    hwTitle: "Hardware Transcoding Support",
    name: "Name",
    description: "Description",
    cpu: "CPU",
    cpuTemp: "CPU Temp",
    usage: "Usage",
    total: "Total",
    free: "Free",
    used: "Used",
    freeSpace: "Free space",
    path: "Path",
    transcode: "Transcode",
    completed: "Completed",
    intelQsv: "Intel QuickSync",
    nvenc: "Nvidia NVENC",
    amdVcn: "AMD VCN",
    hwInfoTooltip: "Reported by HandBrake hardware probe on the server.",
  },
  footer: {
    line: "Automatic Ripping Machine. Find us on",
    github: "GitHub",
  },
} as const;
