/** Single locale bundle for the SPA (split later if i18n is needed). */
export const labels = {
  appTitle: 'ARM',
  appSubtitle: 'Automatic Ripping Machine',
  nav: {
    home: 'Home',
    login: 'Login',
    logout: 'Logout',
    darkMode: 'Dark mode',
  },
  refresh: {
    label: 'Refresh',
    ariaLabel: 'Refresh system information',
  },
  home: {
    welcome: 'Welcome to your Automatic Ripping Machine',
    activeRips: 'Active Rips',
    activeRipsEmpty: 'No active rips.',
    systemInformation: 'System Information',
    loginToViewSystem: 'Log in to load system information.',
    loadError: 'Could not load system data.',
  },
  login: {
    title: 'Sign in',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    error: 'Sign-in failed. Check your email and password.',
  },
  system: {
    cardTitle: 'System',
    memoryTitle: 'System Memory',
    storageTitle: 'Storage',
    hwTitle: 'Hardware Transcoding Support',
    name: 'Name',
    description: 'Description',
    cpu: 'CPU',
    cpuTemp: 'CPU Temp',
    usage: 'Usage',
    total: 'Total',
    free: 'Free',
    used: 'Used',
    freeSpace: 'Free space',
    path: 'Path',
    transcode: 'Transcode',
    completed: 'Completed',
    intelQsv: 'Intel QuickSync',
    nvenc: 'Nvidia NVENC',
    amdVcn: 'AMD VCN',
    hwInfoTooltip: 'Reported by HandBrake hardware probe on the server.',
  },
  footer: {
    line: 'Automatic Ripping Machine. Find us on',
    github: 'GitHub',
  },
} as const
